<?php

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    function antomGooglePay() {
        return antomElementPayment({
            methodCode: '<?= $escaper->escapeJs('antom_googlepay') ?>',
            sdkPaymentMethodType: '<?= $escaper->escapeJs('GOOGLEPAY') ?>',
            containerId: '<?= $escaper->escapeJs('antom-googlepay-container') ?>'
        });
    }

    window.addEventListener('alpine:init', () => Alpine.data('antomGooglePay', antomGooglePay), { once: true });
</script>
<?php $hyvaCsp->registerInlineScript(); ?>
