<?php

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    function antomCard() {
        return antomElementPayment({
            methodCode: '<?= $escaper->escapeJs('antom_cc') ?>',
            sdkPaymentMethodType: '<?= $escaper->escapeJs('CARD') ?>',
            containerId: '<?= $escaper->escapeJs('antom-card-container') ?>'
        });
    }

    window.addEventListener('alpine:init', () => Alpine.data('antomCard', antomCard), { once: true });
</script>
<?php $hyvaCsp->registerInlineScript(); ?>
