<?php

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
?>

<script>
    antomRegisterPaymentMethod({
        methodCode: '<?= $escaper->escapeJs('antom_cc') ?>',
        sdkPaymentMethodType: '<?= $escaper->escapeJs('CARD') ?>',
        containerId: '<?= $escaper->escapeJs('antom-card-container') ?>'
    });
</script>
<?php $hyvaCsp->registerInlineScript(); ?>
